import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App Sample One',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>{metadata.title}</h1>
        </header>
        {children}
        <footer>
          <p>{metadata.description}</p>
        </footer>
        </body>
    </html>
  )
}
